"""Database update

Revision ID: 034303e9368b
Revises: 1225acd0b5fc
Create Date: 2023-07-25 13:09:11.482307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034303e9368b'
down_revision = '1225acd0b5fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('information', schema=None) as batch_op:
        batch_op.drop_column('answer_3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_3', sa.VARCHAR(length=500), nullable=False))

    # ### end Alembic commands ###
