"""Update Information model

Revision ID: 203419a40925
Revises: 05dbfcfc6825
Create Date: 2023-07-18 20:11:54.570755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203419a40925'
down_revision = '05dbfcfc6825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_index', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('answer_1', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('answer_2', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('answer_3', sa.String(length=500), nullable=False))
        batch_op.drop_column('question')
        batch_op.drop_column('answer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.VARCHAR(length=500), nullable=False))
        batch_op.add_column(sa.Column('question', sa.VARCHAR(length=500), nullable=False))
        batch_op.drop_column('answer_3')
        batch_op.drop_column('answer_2')
        batch_op.drop_column('answer_1')
        batch_op.drop_column('conversation_index')

    # ### end Alembic commands ###
