"""Database update

Revision ID: bf8db3187bfc
Revises: 034303e9368b
Create Date: 2023-07-25 14:23:05.334370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8db3187bfc'
down_revision = '034303e9368b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('information', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
